// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logs.sql

package repo

import (
	"context"
)

const deleteLogRecordsOlderThan = `-- name: DeleteLogRecordsOlderThan :exec
DELETE FROM log_records WHERE ingested_at < unixepoch() - ?
`

func (q *Queries) DeleteLogRecordsOlderThan(ctx context.Context, dollar_1 interface{}) error {
	_, err := q.db.ExecContext(ctx, deleteLogRecordsOlderThan, dollar_1)
	return err
}

const insertLogRecord = `-- name: InsertLogRecord :exec
INSERT INTO log_records (
    trace_id,
    span_id,
    service_name,
    severity,
    severity_text,
    body,
    attributes,
    resource_attrs,
    timestamp_ns
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertLogRecordParams struct {
	TraceID       *string `json:"trace_id"`
	SpanID        *string `json:"span_id"`
	ServiceName   string  `json:"service_name"`
	Severity      *int64  `json:"severity"`
	SeverityText  *string `json:"severity_text"`
	Body          *string `json:"body"`
	Attributes    *string `json:"attributes"`
	ResourceAttrs *string `json:"resource_attrs"`
	TimestampNs   int64   `json:"timestamp_ns"`
}

func (q *Queries) InsertLogRecord(ctx context.Context, arg InsertLogRecordParams) error {
	_, err := q.db.ExecContext(ctx, insertLogRecord,
		arg.TraceID,
		arg.SpanID,
		arg.ServiceName,
		arg.Severity,
		arg.SeverityText,
		arg.Body,
		arg.Attributes,
		arg.ResourceAttrs,
		arg.TimestampNs,
	)
	return err
}

const listLogRecordsByService = `-- name: ListLogRecordsByService :many
SELECT id, trace_id, span_id, service_name, severity, severity_text, body, attributes, resource_attrs, timestamp_ns, ingested_at FROM log_records
WHERE service_name = ?
ORDER BY timestamp_ns DESC
LIMIT ? OFFSET ?
`

type ListLogRecordsByServiceParams struct {
	ServiceName string `json:"service_name"`
	Limit       int64  `json:"limit"`
	Offset      int64  `json:"offset"`
}

func (q *Queries) ListLogRecordsByService(ctx context.Context, arg ListLogRecordsByServiceParams) ([]LogRecord, error) {
	rows, err := q.db.QueryContext(ctx, listLogRecordsByService, arg.ServiceName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogRecord
	for rows.Next() {
		var i LogRecord
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.SpanID,
			&i.ServiceName,
			&i.Severity,
			&i.SeverityText,
			&i.Body,
			&i.Attributes,
			&i.ResourceAttrs,
			&i.TimestampNs,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogRecordsBySeverity = `-- name: ListLogRecordsBySeverity :many
SELECT id, trace_id, span_id, service_name, severity, severity_text, body, attributes, resource_attrs, timestamp_ns, ingested_at FROM log_records
WHERE severity = ?
ORDER BY timestamp_ns DESC
LIMIT ? OFFSET ?
`

type ListLogRecordsBySeverityParams struct {
	Severity *int64 `json:"severity"`
	Limit    int64  `json:"limit"`
	Offset   int64  `json:"offset"`
}

func (q *Queries) ListLogRecordsBySeverity(ctx context.Context, arg ListLogRecordsBySeverityParams) ([]LogRecord, error) {
	rows, err := q.db.QueryContext(ctx, listLogRecordsBySeverity, arg.Severity, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogRecord
	for rows.Next() {
		var i LogRecord
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.SpanID,
			&i.ServiceName,
			&i.Severity,
			&i.SeverityText,
			&i.Body,
			&i.Attributes,
			&i.ResourceAttrs,
			&i.TimestampNs,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogRecordsByTimeRange = `-- name: ListLogRecordsByTimeRange :many
SELECT id, trace_id, span_id, service_name, severity, severity_text, body, attributes, resource_attrs, timestamp_ns, ingested_at FROM log_records
WHERE timestamp_ns >= ?
  AND timestamp_ns <= ?
ORDER BY timestamp_ns ASC
`

type ListLogRecordsByTimeRangeParams struct {
	TimestampNs   int64 `json:"timestamp_ns"`
	TimestampNs_2 int64 `json:"timestamp_ns_2"`
}

func (q *Queries) ListLogRecordsByTimeRange(ctx context.Context, arg ListLogRecordsByTimeRangeParams) ([]LogRecord, error) {
	rows, err := q.db.QueryContext(ctx, listLogRecordsByTimeRange, arg.TimestampNs, arg.TimestampNs_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogRecord
	for rows.Next() {
		var i LogRecord
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.SpanID,
			&i.ServiceName,
			&i.Severity,
			&i.SeverityText,
			&i.Body,
			&i.Attributes,
			&i.ResourceAttrs,
			&i.TimestampNs,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogRecordsByTrace = `-- name: ListLogRecordsByTrace :many
SELECT id, trace_id, span_id, service_name, severity, severity_text, body, attributes, resource_attrs, timestamp_ns, ingested_at FROM log_records
WHERE trace_id = ?
ORDER BY timestamp_ns ASC
`

func (q *Queries) ListLogRecordsByTrace(ctx context.Context, traceID *string) ([]LogRecord, error) {
	rows, err := q.db.QueryContext(ctx, listLogRecordsByTrace, traceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogRecord
	for rows.Next() {
		var i LogRecord
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.SpanID,
			&i.ServiceName,
			&i.Severity,
			&i.SeverityText,
			&i.Body,
			&i.Attributes,
			&i.ResourceAttrs,
			&i.TimestampNs,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentLogRecords = `-- name: ListRecentLogRecords :many
SELECT id, trace_id, span_id, service_name, severity, severity_text, body, attributes, resource_attrs, timestamp_ns, ingested_at FROM log_records
ORDER BY timestamp_ns DESC
LIMIT ? OFFSET ?
`

type ListRecentLogRecordsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListRecentLogRecords(ctx context.Context, arg ListRecentLogRecordsParams) ([]LogRecord, error) {
	rows, err := q.db.QueryContext(ctx, listRecentLogRecords, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogRecord
	for rows.Next() {
		var i LogRecord
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.SpanID,
			&i.ServiceName,
			&i.Severity,
			&i.SeverityText,
			&i.Body,
			&i.Attributes,
			&i.ResourceAttrs,
			&i.TimestampNs,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
