// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package repo

import (
	"context"
)

const deleteMetricPointsByName = `-- name: DeleteMetricPointsByName :exec
DELETE FROM metric_points WHERE name = ?
`

func (q *Queries) DeleteMetricPointsByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteMetricPointsByName, name)
	return err
}

const deleteMetricPointsByService = `-- name: DeleteMetricPointsByService :exec
DELETE FROM metric_points WHERE service_name = ?
`

func (q *Queries) DeleteMetricPointsByService(ctx context.Context, serviceName string) error {
	_, err := q.db.ExecContext(ctx, deleteMetricPointsByService, serviceName)
	return err
}

const deleteMetricPointsOlderThan = `-- name: DeleteMetricPointsOlderThan :exec
DELETE FROM metric_points WHERE ingested_at < unixepoch() - ?
`

func (q *Queries) DeleteMetricPointsOlderThan(ctx context.Context, dollar_1 interface{}) error {
	_, err := q.db.ExecContext(ctx, deleteMetricPointsOlderThan, dollar_1)
	return err
}

const getFirstMetricTimestamp = `-- name: GetFirstMetricTimestamp :one
SELECT MIN(timestamp_ns) FROM metric_points WHERE name = ?
`

func (q *Queries) GetFirstMetricTimestamp(ctx context.Context, name string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getFirstMetricTimestamp, name)
	var min interface{}
	err := row.Scan(&min)
	return min, err
}

const getLastMetricTimestamp = `-- name: GetLastMetricTimestamp :one
SELECT MAX(timestamp_ns) FROM metric_points WHERE name = ?
`

func (q *Queries) GetLastMetricTimestamp(ctx context.Context, name string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLastMetricTimestamp, name)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const getMetricPoint = `-- name: GetMetricPoint :one
SELECT id, name, description, unit, type, service_name, attributes, timestamp_ns, value_int, value_double, hist_count, hist_sum, hist_bounds, hist_counts, resource_attrs, ingested_at FROM metric_points WHERE id = ? LIMIT 1
`

func (q *Queries) GetMetricPoint(ctx context.Context, id int64) (MetricPoint, error) {
	row := q.db.QueryRowContext(ctx, getMetricPoint, id)
	var i MetricPoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Unit,
		&i.Type,
		&i.ServiceName,
		&i.Attributes,
		&i.TimestampNs,
		&i.ValueInt,
		&i.ValueDouble,
		&i.HistCount,
		&i.HistSum,
		&i.HistBounds,
		&i.HistCounts,
		&i.ResourceAttrs,
		&i.IngestedAt,
	)
	return i, err
}

const getMetricPointCountByName = `-- name: GetMetricPointCountByName :one
SELECT COUNT(*) FROM metric_points WHERE name = ?
`

func (q *Queries) GetMetricPointCountByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMetricPointCountByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMetricPointCountByService = `-- name: GetMetricPointCountByService :one
SELECT COUNT(*) FROM metric_points WHERE service_name = ?
`

func (q *Queries) GetMetricPointCountByService(ctx context.Context, serviceName string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMetricPointCountByService, serviceName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertMetricPoint = `-- name: InsertMetricPoint :exec
INSERT INTO metric_points (
    name,
    description,
    unit,
    type,
    service_name,
    attributes,
    timestamp_ns,
    value_int,
    value_double,
    hist_count,
    hist_sum,
    hist_bounds,
    hist_counts,
    resource_attrs
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertMetricPointParams struct {
	Name          string   `json:"name"`
	Description   *string  `json:"description"`
	Unit          *string  `json:"unit"`
	Type          int64    `json:"type"`
	ServiceName   string   `json:"service_name"`
	Attributes    *string  `json:"attributes"`
	TimestampNs   int64    `json:"timestamp_ns"`
	ValueInt      *int64   `json:"value_int"`
	ValueDouble   *float64 `json:"value_double"`
	HistCount     *int64   `json:"hist_count"`
	HistSum       *float64 `json:"hist_sum"`
	HistBounds    *string  `json:"hist_bounds"`
	HistCounts    *string  `json:"hist_counts"`
	ResourceAttrs *string  `json:"resource_attrs"`
}

func (q *Queries) InsertMetricPoint(ctx context.Context, arg InsertMetricPointParams) error {
	_, err := q.db.ExecContext(ctx, insertMetricPoint,
		arg.Name,
		arg.Description,
		arg.Unit,
		arg.Type,
		arg.ServiceName,
		arg.Attributes,
		arg.TimestampNs,
		arg.ValueInt,
		arg.ValueDouble,
		arg.HistCount,
		arg.HistSum,
		arg.HistBounds,
		arg.HistCounts,
		arg.ResourceAttrs,
	)
	return err
}

const listMetricNames = `-- name: ListMetricNames :many
SELECT DISTINCT name FROM metric_points ORDER BY name
`

func (q *Queries) ListMetricNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMetricNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricNamesByService = `-- name: ListMetricNamesByService :many
SELECT DISTINCT name FROM metric_points
WHERE service_name = ?
ORDER BY name
`

func (q *Queries) ListMetricNamesByService(ctx context.Context, serviceName string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMetricNamesByService, serviceName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricPointsByName = `-- name: ListMetricPointsByName :many
SELECT id, name, description, unit, type, service_name, attributes, timestamp_ns, value_int, value_double, hist_count, hist_sum, hist_bounds, hist_counts, resource_attrs, ingested_at FROM metric_points
WHERE name = ?
ORDER BY timestamp_ns DESC
LIMIT ? OFFSET ?
`

type ListMetricPointsByNameParams struct {
	Name   string `json:"name"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListMetricPointsByName(ctx context.Context, arg ListMetricPointsByNameParams) ([]MetricPoint, error) {
	rows, err := q.db.QueryContext(ctx, listMetricPointsByName, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetricPoint
	for rows.Next() {
		var i MetricPoint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Unit,
			&i.Type,
			&i.ServiceName,
			&i.Attributes,
			&i.TimestampNs,
			&i.ValueInt,
			&i.ValueDouble,
			&i.HistCount,
			&i.HistSum,
			&i.HistBounds,
			&i.HistCounts,
			&i.ResourceAttrs,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricPointsByNameAndTimeRange = `-- name: ListMetricPointsByNameAndTimeRange :many
SELECT id, name, description, unit, type, service_name, attributes, timestamp_ns, value_int, value_double, hist_count, hist_sum, hist_bounds, hist_counts, resource_attrs, ingested_at FROM metric_points
WHERE name = ?
  AND timestamp_ns >= ?
  AND timestamp_ns <= ?
ORDER BY timestamp_ns ASC
`

type ListMetricPointsByNameAndTimeRangeParams struct {
	Name          string `json:"name"`
	TimestampNs   int64  `json:"timestamp_ns"`
	TimestampNs_2 int64  `json:"timestamp_ns_2"`
}

func (q *Queries) ListMetricPointsByNameAndTimeRange(ctx context.Context, arg ListMetricPointsByNameAndTimeRangeParams) ([]MetricPoint, error) {
	rows, err := q.db.QueryContext(ctx, listMetricPointsByNameAndTimeRange, arg.Name, arg.TimestampNs, arg.TimestampNs_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetricPoint
	for rows.Next() {
		var i MetricPoint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Unit,
			&i.Type,
			&i.ServiceName,
			&i.Attributes,
			&i.TimestampNs,
			&i.ValueInt,
			&i.ValueDouble,
			&i.HistCount,
			&i.HistSum,
			&i.HistBounds,
			&i.HistCounts,
			&i.ResourceAttrs,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricPointsByService = `-- name: ListMetricPointsByService :many
SELECT id, name, description, unit, type, service_name, attributes, timestamp_ns, value_int, value_double, hist_count, hist_sum, hist_bounds, hist_counts, resource_attrs, ingested_at FROM metric_points
WHERE service_name = ?
ORDER BY timestamp_ns DESC
LIMIT ? OFFSET ?
`

type ListMetricPointsByServiceParams struct {
	ServiceName string `json:"service_name"`
	Limit       int64  `json:"limit"`
	Offset      int64  `json:"offset"`
}

func (q *Queries) ListMetricPointsByService(ctx context.Context, arg ListMetricPointsByServiceParams) ([]MetricPoint, error) {
	rows, err := q.db.QueryContext(ctx, listMetricPointsByService, arg.ServiceName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetricPoint
	for rows.Next() {
		var i MetricPoint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Unit,
			&i.Type,
			&i.ServiceName,
			&i.Attributes,
			&i.TimestampNs,
			&i.ValueInt,
			&i.ValueDouble,
			&i.HistCount,
			&i.HistSum,
			&i.HistBounds,
			&i.HistCounts,
			&i.ResourceAttrs,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricPointsByServiceAndTimeRange = `-- name: ListMetricPointsByServiceAndTimeRange :many
SELECT id, name, description, unit, type, service_name, attributes, timestamp_ns, value_int, value_double, hist_count, hist_sum, hist_bounds, hist_counts, resource_attrs, ingested_at FROM metric_points
WHERE service_name = ?
  AND timestamp_ns >= ?
  AND timestamp_ns <= ?
ORDER BY timestamp_ns ASC
`

type ListMetricPointsByServiceAndTimeRangeParams struct {
	ServiceName   string `json:"service_name"`
	TimestampNs   int64  `json:"timestamp_ns"`
	TimestampNs_2 int64  `json:"timestamp_ns_2"`
}

func (q *Queries) ListMetricPointsByServiceAndTimeRange(ctx context.Context, arg ListMetricPointsByServiceAndTimeRangeParams) ([]MetricPoint, error) {
	rows, err := q.db.QueryContext(ctx, listMetricPointsByServiceAndTimeRange, arg.ServiceName, arg.TimestampNs, arg.TimestampNs_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetricPoint
	for rows.Next() {
		var i MetricPoint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Unit,
			&i.Type,
			&i.ServiceName,
			&i.Attributes,
			&i.TimestampNs,
			&i.ValueInt,
			&i.ValueDouble,
			&i.HistCount,
			&i.HistSum,
			&i.HistBounds,
			&i.HistCounts,
			&i.ResourceAttrs,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricPointsByType = `-- name: ListMetricPointsByType :many
SELECT id, name, description, unit, type, service_name, attributes, timestamp_ns, value_int, value_double, hist_count, hist_sum, hist_bounds, hist_counts, resource_attrs, ingested_at FROM metric_points
WHERE type = ?
ORDER BY timestamp_ns DESC
LIMIT ? OFFSET ?
`

type ListMetricPointsByTypeParams struct {
	Type   int64 `json:"type"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListMetricPointsByType(ctx context.Context, arg ListMetricPointsByTypeParams) ([]MetricPoint, error) {
	rows, err := q.db.QueryContext(ctx, listMetricPointsByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetricPoint
	for rows.Next() {
		var i MetricPoint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Unit,
			&i.Type,
			&i.ServiceName,
			&i.Attributes,
			&i.TimestampNs,
			&i.ValueInt,
			&i.ValueDouble,
			&i.HistCount,
			&i.HistSum,
			&i.HistBounds,
			&i.HistCounts,
			&i.ResourceAttrs,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMetricPoints = `-- name: ListRecentMetricPoints :many
SELECT id, name, description, unit, type, service_name, attributes, timestamp_ns, value_int, value_double, hist_count, hist_sum, hist_bounds, hist_counts, resource_attrs, ingested_at FROM metric_points
ORDER BY timestamp_ns DESC
LIMIT ? OFFSET ?
`

type ListRecentMetricPointsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListRecentMetricPoints(ctx context.Context, arg ListRecentMetricPointsParams) ([]MetricPoint, error) {
	rows, err := q.db.QueryContext(ctx, listRecentMetricPoints, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetricPoint
	for rows.Next() {
		var i MetricPoint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Unit,
			&i.Type,
			&i.ServiceName,
			&i.Attributes,
			&i.TimestampNs,
			&i.ValueInt,
			&i.ValueDouble,
			&i.HistCount,
			&i.HistSum,
			&i.HistBounds,
			&i.HistCounts,
			&i.ResourceAttrs,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesWithMetrics = `-- name: ListServicesWithMetrics :many
SELECT DISTINCT service_name FROM metric_points ORDER BY service_name
`

func (q *Queries) ListServicesWithMetrics(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listServicesWithMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var service_name string
		if err := rows.Scan(&service_name); err != nil {
			return nil, err
		}
		items = append(items, service_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
