// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

type LogRecord struct {
	ID            int64   `json:"id"`
	TraceID       *string `json:"trace_id"`
	SpanID        *string `json:"span_id"`
	ServiceName   string  `json:"service_name"`
	Severity      *int64  `json:"severity"`
	SeverityText  *string `json:"severity_text"`
	Body          *string `json:"body"`
	Attributes    *string `json:"attributes"`
	ResourceAttrs *string `json:"resource_attrs"`
	TimestampNs   int64   `json:"timestamp_ns"`
	IngestedAt    int64   `json:"ingested_at"`
}

type MetricPoint struct {
	ID            int64    `json:"id"`
	Name          string   `json:"name"`
	Description   *string  `json:"description"`
	Unit          *string  `json:"unit"`
	Type          int64    `json:"type"`
	ServiceName   string   `json:"service_name"`
	Attributes    *string  `json:"attributes"`
	TimestampNs   int64    `json:"timestamp_ns"`
	ValueInt      *int64   `json:"value_int"`
	ValueDouble   *float64 `json:"value_double"`
	HistCount     *int64   `json:"hist_count"`
	HistSum       *float64 `json:"hist_sum"`
	HistBounds    *string  `json:"hist_bounds"`
	HistCounts    *string  `json:"hist_counts"`
	ResourceAttrs *string  `json:"resource_attrs"`
	IngestedAt    int64    `json:"ingested_at"`
}

type Span struct {
	SpanID        string  `json:"span_id"`
	TraceID       string  `json:"trace_id"`
	ParentSpanID  *string `json:"parent_span_id"`
	Name          string  `json:"name"`
	ServiceName   string  `json:"service_name"`
	SpanKind      int64   `json:"span_kind"`
	StartTimeNs   int64   `json:"start_time_ns"`
	EndTimeNs     int64   `json:"end_time_ns"`
	DurationNs    *int64  `json:"duration_ns"`
	StatusCode    int64   `json:"status_code"`
	StatusMessage *string `json:"status_message"`
	Attributes    *string `json:"attributes"`
	Events        *string `json:"events"`
	ResourceAttrs *string `json:"resource_attrs"`
	IngestedAt    int64   `json:"ingested_at"`
}
