// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spans.sql

package repo

import (
	"context"
)

const deleteSpansOlderThan = `-- name: DeleteSpansOlderThan :exec
DELETE FROM spans
WHERE ingested_at < unixepoch() - ?
`

func (q *Queries) DeleteSpansOlderThan(ctx context.Context, dollar_1 interface{}) error {
	_, err := q.db.ExecContext(ctx, deleteSpansOlderThan, dollar_1)
	return err
}

const getSpan = `-- name: GetSpan :one
SELECT span_id, trace_id, parent_span_id, name, service_name, span_kind, start_time_ns, end_time_ns, duration_ns, status_code, status_message, attributes, events, resource_attrs, ingested_at FROM spans
WHERE trace_id = ? AND span_id = ?
LIMIT 1
`

type GetSpanParams struct {
	TraceID string `json:"trace_id"`
	SpanID  string `json:"span_id"`
}

func (q *Queries) GetSpan(ctx context.Context, arg GetSpanParams) (Span, error) {
	row := q.db.QueryRowContext(ctx, getSpan, arg.TraceID, arg.SpanID)
	var i Span
	err := row.Scan(
		&i.SpanID,
		&i.TraceID,
		&i.ParentSpanID,
		&i.Name,
		&i.ServiceName,
		&i.SpanKind,
		&i.StartTimeNs,
		&i.EndTimeNs,
		&i.DurationNs,
		&i.StatusCode,
		&i.StatusMessage,
		&i.Attributes,
		&i.Events,
		&i.ResourceAttrs,
		&i.IngestedAt,
	)
	return i, err
}

const insertSpan = `-- name: InsertSpan :exec
INSERT INTO spans (
    span_id, trace_id, parent_span_id, name, service_name,
    span_kind, start_time_ns, end_time_ns,
    status_code, status_message, attributes, events, resource_attrs
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?, ?, ?
)
`

type InsertSpanParams struct {
	SpanID        string  `json:"span_id"`
	TraceID       string  `json:"trace_id"`
	ParentSpanID  *string `json:"parent_span_id"`
	Name          string  `json:"name"`
	ServiceName   string  `json:"service_name"`
	SpanKind      int64   `json:"span_kind"`
	StartTimeNs   int64   `json:"start_time_ns"`
	EndTimeNs     int64   `json:"end_time_ns"`
	StatusCode    int64   `json:"status_code"`
	StatusMessage *string `json:"status_message"`
	Attributes    *string `json:"attributes"`
	Events        *string `json:"events"`
	ResourceAttrs *string `json:"resource_attrs"`
}

func (q *Queries) InsertSpan(ctx context.Context, arg InsertSpanParams) error {
	_, err := q.db.ExecContext(ctx, insertSpan,
		arg.SpanID,
		arg.TraceID,
		arg.ParentSpanID,
		arg.Name,
		arg.ServiceName,
		arg.SpanKind,
		arg.StartTimeNs,
		arg.EndTimeNs,
		arg.StatusCode,
		arg.StatusMessage,
		arg.Attributes,
		arg.Events,
		arg.ResourceAttrs,
	)
	return err
}

const listRecentSpans = `-- name: ListRecentSpans :many
SELECT span_id, trace_id, parent_span_id, name, service_name, span_kind, start_time_ns, end_time_ns, duration_ns, status_code, status_message, attributes, events, resource_attrs, ingested_at FROM spans
ORDER BY start_time_ns DESC
LIMIT ? OFFSET ?
`

type ListRecentSpansParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListRecentSpans(ctx context.Context, arg ListRecentSpansParams) ([]Span, error) {
	rows, err := q.db.QueryContext(ctx, listRecentSpans, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Span
	for rows.Next() {
		var i Span
		if err := rows.Scan(
			&i.SpanID,
			&i.TraceID,
			&i.ParentSpanID,
			&i.Name,
			&i.ServiceName,
			&i.SpanKind,
			&i.StartTimeNs,
			&i.EndTimeNs,
			&i.DurationNs,
			&i.StatusCode,
			&i.StatusMessage,
			&i.Attributes,
			&i.Events,
			&i.ResourceAttrs,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpansByService = `-- name: ListSpansByService :many
SELECT span_id, trace_id, parent_span_id, name, service_name, span_kind, start_time_ns, end_time_ns, duration_ns, status_code, status_message, attributes, events, resource_attrs, ingested_at FROM spans
WHERE service_name = ?
ORDER BY start_time_ns DESC
LIMIT ? OFFSET ?
`

type ListSpansByServiceParams struct {
	ServiceName string `json:"service_name"`
	Limit       int64  `json:"limit"`
	Offset      int64  `json:"offset"`
}

func (q *Queries) ListSpansByService(ctx context.Context, arg ListSpansByServiceParams) ([]Span, error) {
	rows, err := q.db.QueryContext(ctx, listSpansByService, arg.ServiceName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Span
	for rows.Next() {
		var i Span
		if err := rows.Scan(
			&i.SpanID,
			&i.TraceID,
			&i.ParentSpanID,
			&i.Name,
			&i.ServiceName,
			&i.SpanKind,
			&i.StartTimeNs,
			&i.EndTimeNs,
			&i.DurationNs,
			&i.StatusCode,
			&i.StatusMessage,
			&i.Attributes,
			&i.Events,
			&i.ResourceAttrs,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpansByTrace = `-- name: ListSpansByTrace :many
SELECT span_id, trace_id, parent_span_id, name, service_name, span_kind, start_time_ns, end_time_ns, duration_ns, status_code, status_message, attributes, events, resource_attrs, ingested_at FROM spans
WHERE trace_id = ?
ORDER BY start_time_ns ASC
`

func (q *Queries) ListSpansByTrace(ctx context.Context, traceID string) ([]Span, error) {
	rows, err := q.db.QueryContext(ctx, listSpansByTrace, traceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Span
	for rows.Next() {
		var i Span
		if err := rows.Scan(
			&i.SpanID,
			&i.TraceID,
			&i.ParentSpanID,
			&i.Name,
			&i.ServiceName,
			&i.SpanKind,
			&i.StartTimeNs,
			&i.EndTimeNs,
			&i.DurationNs,
			&i.StatusCode,
			&i.StatusMessage,
			&i.Attributes,
			&i.Events,
			&i.ResourceAttrs,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTraceSummaries = `-- name: ListTraceSummaries :many
SELECT
    trace_id                                             AS trace_id,
    CAST(MIN(start_time_ns) AS INTEGER)                  AS start_time_ns,
    CAST(MAX(end_time_ns) - MIN(start_time_ns) AS INTEGER) AS duration_ns,
    CAST(COUNT(*) AS INTEGER)                            AS span_count,
    CAST(MAX(CASE WHEN status_code = 2 THEN 1 ELSE 0 END) AS INTEGER) AS has_errors,
    CAST(COALESCE(
        (
            SELECT s2.service_name FROM spans s2
            WHERE s2.trace_id = spans.trace_id AND s2.parent_span_id IS NULL
            LIMIT 1
        ),
        ''
    ) AS TEXT)                                           AS root_service,
    CAST(COALESCE(
        (
            SELECT s2.name FROM spans s2
            WHERE s2.trace_id = spans.trace_id AND s2.parent_span_id IS NULL
            LIMIT 1
        ),
        ''
    ) AS TEXT)                                           AS root_name
FROM spans
GROUP BY trace_id
ORDER BY start_time_ns DESC
LIMIT ? OFFSET ?
`

type ListTraceSummariesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListTraceSummariesRow struct {
	TraceID     string `json:"trace_id"`
	StartTimeNs int64  `json:"start_time_ns"`
	DurationNs  int64  `json:"duration_ns"`
	SpanCount   int64  `json:"span_count"`
	HasErrors   int64  `json:"has_errors"`
	RootService string `json:"root_service"`
	RootName    string `json:"root_name"`
}

// Aggregates spans per trace_id for the TUI list view.
// root_service/root_name come from the span with NULL parent_span_id (the root).
func (q *Queries) ListTraceSummaries(ctx context.Context, arg ListTraceSummariesParams) ([]ListTraceSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTraceSummaries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTraceSummariesRow
	for rows.Next() {
		var i ListTraceSummariesRow
		if err := rows.Scan(
			&i.TraceID,
			&i.StartTimeNs,
			&i.DurationNs,
			&i.SpanCount,
			&i.HasErrors,
			&i.RootService,
			&i.RootName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
