// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Span struct {
	SpanID        string  `json:"span_id"`
	TraceID       string  `json:"trace_id"`
	ParentSpanID  *string `json:"parent_span_id"`
	Name          string  `json:"name"`
	ServiceName   string  `json:"service_name"`
	SpanKind      int64   `json:"span_kind"`
	StartTimeNs   int64   `json:"start_time_ns"`
	EndTimeNs     int64   `json:"end_time_ns"`
	DurationNs    *int64  `json:"duration_ns"`
	StatusCode    int64   `json:"status_code"`
	StatusMessage *string `json:"status_message"`
	Attributes    *string `json:"attributes"`
	Events        *string `json:"events"`
	ResourceAttrs *string `json:"resource_attrs"`
	IngestedAt    int64   `json:"ingested_at"`
}
